library(shiny)
library(shinydashboard)
library(shinycssloaders)
library(DT)
library(tidyverse)
library(colourpicker)
library(Cairo)
library(openxlsx)
library(data.table)
library(future.apply)
library(writexl)

source("script/gwas_emmax_cov.R")
source("script/extraxt_gene.R")
source("script/manhattan_qq_plot.R")
load("./data/Bna_gene_anno.RData")

